// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface PlacesResponse {
    type:        string;
    query:       string[];
    features:    Feature[];
    attribution: string;
}

export interface Feature {
    id:               string;
    type:             string;
    place_type:       string[];
    relevance:        number;
    properties:       Properties;
    routable_points?: RoutablePoints;
    text_en:          string;
    language_en?:     string;
    place_name_en:    string;
    text:             string;
    language?:        string;
    place_name:       string;
    center:           number[];
    geometry:         Geometry;
    context:          Context[];
}

export interface Context {
    id:           string;
    mapbox_id:    string;
    text_en:      string;
    text:         string;
    wikidata?:    string;
    short_code?:  string;
    language_en?: string;
    language?:    string;
}

export interface Geometry {
    coordinates: number[];
    type:        string;
}

export interface Properties {
    foursquare?: string;
    landmark?:   boolean;
    address?:    string;
    category?:   string;
    maki?:       string;
    accuracy?:   string;
    mapbox_id?:  string;
}

export interface RoutablePoints {
    points: null;
}
